version: "3.8"
services:
  backend:
    image: "hmhs97/springboot-react-fullstack:22.7.2021.7.49.1"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev

