version: "3.8"
services:
  backend:
    image: "hmhs97/springboot-react-fullstack:21.7.2021.19.47.26"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev

