version: "3.8"
services:
  backend:
    image: "hmhs97/springboot-react-fullstack:24.7.2021.10.15.45"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev

