version: "3.8"
services:
  backend:
    image: "hmhs97/springboot-react-fullstack:23.7.2021.16.48.21"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev

